-- Event registration v2 tables (header + line items + pending mirrors)

CREATE TABLE IF NOT EXISTS `event_registration` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `event_id` INT UNSIGNED NOT NULL,
    `registration_mode` ENUM('individual', 'group_flat', 'group_per_head') NOT NULL DEFAULT 'individual',
    `confirmation_number` VARCHAR(32) NOT NULL,
    `member_count` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `subtotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `discount_total` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `pricing_snapshot` JSON NULL,
    `form_schema_snapshot` JSON NULL,
    `promo_id` INT UNSIGNED NULL DEFAULT NULL,
    `payment_status` ENUM('pending', 'paid', 'failed', 'free', 'refunded') NOT NULL DEFAULT 'pending',
    `payment_request_id` VARCHAR(64) NULL DEFAULT NULL,
    `payment_option` VARCHAR(32) NOT NULL DEFAULT 'N/A',
    `primary_email` VARCHAR(255) NOT NULL DEFAULT '',
    `primary_order_number` VARCHAR(32) NOT NULL DEFAULT '',
    `is_email_confirmation_sent` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `paid_at` DATETIME NULL DEFAULT NULL,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_confirmation_number` (`confirmation_number`),
    KEY `idx_event_id` (`event_id`),
    KEY `idx_payment_request_id` (`payment_request_id`),
    KEY `idx_primary_email_event` (`primary_email`, `event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_registrant` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `registration_id` INT UNSIGNED NOT NULL,
    `event_id` INT UNSIGNED NOT NULL,
    `member_index` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `role` ENUM('primary', 'member', 'addon') NOT NULL DEFAULT 'primary',
    `order_number` VARCHAR(32) NOT NULL DEFAULT '',
    `nric` VARCHAR(4) NULL DEFAULT NULL,
    `title` VARCHAR(10) NULL DEFAULT NULL,
    `christian_name` VARCHAR(100) NULL DEFAULT NULL,
    `given_name` VARCHAR(100) NULL DEFAULT NULL,
    `family_name` VARCHAR(100) NULL DEFAULT NULL,
    `certificate_name` VARCHAR(200) NULL DEFAULT NULL,
    `email` VARCHAR(255) NULL DEFAULT NULL,
    `contact` VARCHAR(30) NULL DEFAULT NULL,
    `address1` VARCHAR(255) NULL DEFAULT NULL,
    `address2` VARCHAR(255) NULL DEFAULT NULL,
    `postcode` VARCHAR(10) NULL DEFAULT NULL,
    `church_name` VARCHAR(200) NULL DEFAULT NULL,
    `custom_responses` JSON NULL,
    `unit_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `discount_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    `status` ENUM('pending', 'confirmed', 'cancelled') NOT NULL DEFAULT 'pending',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_order_number` (`order_number`),
    KEY `idx_registration_id` (`registration_id`),
    KEY `idx_event_id` (`event_id`),
    KEY `idx_email_event` (`email`, `event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_registration_pendings` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `event_id` INT UNSIGNED NOT NULL,
    `registration_mode` ENUM('individual', 'group_flat', 'group_per_head') NOT NULL DEFAULT 'individual',
    `confirmation_number` VARCHAR(32) NOT NULL,
    `member_count` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `subtotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `discount_total` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `pricing_snapshot` JSON NULL,
    `form_schema_snapshot` JSON NULL,
    `promo_id` INT UNSIGNED NULL DEFAULT NULL,
    `payment_status` ENUM('pending', 'paid', 'failed', 'free', 'refunded') NOT NULL DEFAULT 'pending',
    `payment_request_id` VARCHAR(64) NULL DEFAULT NULL,
    `payment_option` VARCHAR(32) NOT NULL DEFAULT 'N/A',
    `primary_email` VARCHAR(255) NOT NULL DEFAULT '',
    `primary_order_number` VARCHAR(32) NOT NULL DEFAULT '',
    `is_email_confirmation_sent` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_confirmation_number` (`confirmation_number`),
    KEY `idx_event_id` (`event_id`),
    KEY `idx_payment_request_id` (`payment_request_id`),
    KEY `idx_primary_email_event` (`primary_email`, `event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_registrant_pendings` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `registration_id` INT UNSIGNED NOT NULL,
    `event_id` INT UNSIGNED NOT NULL,
    `member_index` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `role` ENUM('primary', 'member', 'addon') NOT NULL DEFAULT 'primary',
    `order_number` VARCHAR(32) NOT NULL DEFAULT '',
    `nric` VARCHAR(4) NULL DEFAULT NULL,
    `title` VARCHAR(10) NULL DEFAULT NULL,
    `christian_name` VARCHAR(100) NULL DEFAULT NULL,
    `given_name` VARCHAR(100) NULL DEFAULT NULL,
    `family_name` VARCHAR(100) NULL DEFAULT NULL,
    `certificate_name` VARCHAR(200) NULL DEFAULT NULL,
    `email` VARCHAR(255) NULL DEFAULT NULL,
    `contact` VARCHAR(30) NULL DEFAULT NULL,
    `address1` VARCHAR(255) NULL DEFAULT NULL,
    `address2` VARCHAR(255) NULL DEFAULT NULL,
    `postcode` VARCHAR(10) NULL DEFAULT NULL,
    `church_name` VARCHAR(200) NULL DEFAULT NULL,
    `custom_responses` JSON NULL,
    `unit_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `discount_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    `status` ENUM('pending', 'confirmed', 'cancelled') NOT NULL DEFAULT 'pending',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_registration_id` (`registration_id`),
    KEY `idx_event_id` (`event_id`),
    KEY `idx_email_event` (`email`, `event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
